DROP DATABASE IF EXISTS carservice;
DROP USER IF EXISTS carservice;
CREATE USER carservice WITH ENCRYPTED PASSWORD '123';
CREATE DATABASE carservice WITH OWNER carservice;

-- drop table cars cascade ;
-- drop table services cascade ;
-- drop table master cascade ;
-- drop table works cascade ;
-- drop table users cascade ;


CREATE TABLE cars
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    num        VARCHAR,
    color      VARCHAR,
    mark       VARCHAR,
    is_foreign BOOLEAN
);

CREATE TABLE masters
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR
);

CREATE TABLE services
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR,
    cost_our     INTEGER,
    cost_foreign INTEGER
);

CREATE TABLE works
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date_work  TIMESTAMP,
    masters_id  BIGINT REFERENCES masters (id) ON DELETE CASCADE ON UPDATE CASCADE,
    cars_id     BIGINT REFERENCES cars (id) ON DELETE CASCADE ON UPDATE CASCADE,
    services_id BIGINT REFERENCES services (id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR,
    password VARCHAR
);

CREATE TABLE user_roles
(
    user_id    BIGINT REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE,
    roles VARCHAR
);